### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Disa-Kizonda** [shg8/VulkanSplatting#6]
https://github.com/shg8/VulkanSplatting/assets/53359732/09abba2a-4fd8-4c7a-8fca-5e96a8f18191

**Comment by shg8** [comment]
How large is your scene? Try reducing [this](https://github.com/shg8/VulkanSplatting/blob/72da9906823c10f41ae5786523c50ea1645405cc/3dgs/Renderer.cpp#L16C34-L16C37) to 10.

**Comment by Disa-Kizonda** [comment]
Nothing changed
I tried on iteration 100 and reduced to 10

**Comment by shg8** [comment]
Could you pull the latest commit and do a Release build? It should print some errors now

**Comment by Disa-Kizonda** [comment]
![image](https://github.com/shg8/VulkanSplatting/assets/53359732/50e91b1b-c8d8-448a-8ed8-22cc172ca44b)

**Comment by shg8** [comment]
Hmm there should be more errors. Make sure you cleared the cmake folder and set the build type to Release. Or try downloading a prebuilt version [here](https://github.com/shg8/VulkanSplatting/actions/runs/7927879706).

**Comment by Disa-Kizonda** [comment]
Same with prebuilt

**Comment by shg8** [comment]
I'm not sure why but std::cerr doesn't seem to be printing on your system. I'm running the exact same commands and getting the errors printed out.

**Comment by oUp2Uo** [comment]
Same with @Disa-Kizonda .
On win 10, run the program, came out a window and then shut down.

```
[0] NVIDIA GeForce GTX 1050
[1] Intel(R) UHD Graphics 620
Selected physical device (automatically): NVIDIA GeForce GTX 1050
```

**Comment by shg8** [comment]
> Same with @Disa-Kizonda . On win 10, run the program, came out a window and then shut down.
> 
> ```
> [0] NVIDIA GeForce GTX 1050
> [1] Intel(R) UHD Graphics 620
> Selected physical device (automatically): NVIDIA GeForce GTX 1050
> ```

The errors should be now printing in stdout. Please try the latest build [here](https://github.com/shg8/VulkanSplatting/actions/runs/7982531002).

**Comment by oUp2Uo** [comment]
> > Same with @Disa-Kizonda . On win 10, run the program, came out a window and then shut down.
> > ```
> > [0] NVIDIA GeForce GTX 1050
> > [1] Intel(R) UHD Graphics 620
> > Selected physical device (automatically): NVIDIA GeForce GTX 1050
> > ```
> 
> The errors should be now printing in stdout. Please try the latest build [here](https://github.com/shg8/VulkanSplatting/actions/runs/7982531002).

Still the same, no other new prints.

**Comment by shg8** [comment]
> > > Same with @Disa-Kizonda . On win 10, run the program, came out a window and then shut down.
> > > ```
> > > [0] NVIDIA GeForce GTX 1050
> > > [1] Intel(R) UHD Graphics 620
> > > Selected physical device (automatically): NVIDIA GeForce GTX 1050
> > > ```
> > 
> > 
> > The errors should be now printing in stdout. Please try the latest build [here](https://github.com/shg8/VulkanSplatting/actions/runs/7982531002).
> 
> Still the same, no other new prints.

Could you try the latest build with the -v option? Thanks

**Comment by Disa-Kizonda** [comment]
![image](https://github.com/shg8/VulkanSplatting/assets/53359732/bf8801b1-a77f-4bc8-84b1-f8f20bcaeabb)

**Comment by Disa-Kizonda** [comment]
![image](https://github.com/shg8/VulkanSplatting/assets/53359732/47569fe7-726b-4ec6-8b55-48d864401e91)

**Comment by shg8** [comment]
> ![image](https://private-user-images.githubusercontent.com/53359732/306514282-47569fe7-726b-4ec6-8b55-48d864401e91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTU4NzMsIm5iZiI6MTcwODQ5NTU3MywicGF0aCI6Ii81MzM1OTczMi8zMDY1MTQyODItNDc1NjlmZTctNzI2Yi00ZWM2LThiNTUtNDhkODY0NDAxZTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA2MDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZTQ1MjQyNWUzMmZhNDY4YTg0NjkwYmIzZGFlOGM3MWZiYzBkNzcyMTQ0NTlkMzQzZWMwODJkMjBjNmZhYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tApD0strLvFcbveYiAWVCrlKRLOtfNVi0KOCIXXia04)
> 
> full log from old build [full.txt](https://github.com/shg8/VulkanSplatting/files/14354795/full.txt)

Cool. Now at least the errors are printing. Could you try it with -v --validation now?

**Comment by Disa-Kizonda** [comment]
[full.txt](https://github.com/shg8/VulkanSplatting/files/14354885/full.txt)

**Comment by shg8** [comment]
> [full.txt](https://github.com/shg8/VulkanSplatting/files/14354885/full.txt)

Thanks for the logs. The latest commit should fix it now.

**Comment by oUp2Uo** [comment]
Hi, the latest commit gave out some print.
```
[15:33:47] [C] Failed to load shader: shaders/precomp_cov3d.comp.spv
Failed to load shader: shaders/precomp_cov3d.comp.spv
```
Then I downloaded the `shaders` folder, but could not find the `.spv` file there.

**Comment by shg8** [comment]
> Hi, the latest commit gave out some print.
> 
> ```
> [15:33:47] [C] Failed to load shader: shaders/precomp_cov3d.comp.spv
> Failed to load shader: shaders/precomp_cov3d.comp.spv
> ```
> 
> Then I downloaded the `shaders` folder, but could not find the `.spv` file there.

For now, you'd have to compile them manually or build it from source unfortunately. CMake should handle all of the shader compilation. I'll add bundled shader compilation to my TODO list.

**Comment by Disa-Kizonda** [comment]
It's working now thank you 

![image](https://github.com/shg8/VulkanSplatting/assets/53359732/8312606c-3cd2-4641-82de-1952b61d2cf8)

**Comment by Disa-Kizonda** [comment]
@oUp2Uo 

[shaders.zip](https://github.com/shg8/VulkanSplatting/files/14355598/shaders.zip)

**Comment by oUp2Uo** [comment]
> > Hi, the latest commit gave out some print.
> > ```
> > [15:33:47] [C] Failed to load shader: shaders/precomp_cov3d.comp.spv
> > Failed to load shader: shaders/precomp_cov3d.comp.spv
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then I downloaded the `shaders` folder, but could not find the `.spv` file there.
> 
> For now, you'd have to compile them manually or build it from source unfortunately. CMake should handle all of the shader compilation. I'll add bundled shaders to my TODO list.

I have build the program, and could see the result now!
(Although run out of memory after several seconds)
I will try this on other PC.
Btw, does it means that if I want to run on one PC, I should build it one that PC again?
Thanks.

**Comment by shg8** [comment]
> > > Hi, the latest commit gave out some print.
> > > ```
> > > [15:33:47] [C] Failed to load shader: shaders/precomp_cov3d.comp.spv
> > > Failed to load shader: shaders/precomp_cov3d.comp.spv
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then I downloaded the `shaders` folder, but could not find the `.spv` file there.
> > 
> > 
> > For now, you'd have to compile them manually or build it from source unfortunately. CMake should handle all of the shader compilation. I'll add bundled shaders to my TODO list.
> 
> I have build the program, and could see the result now! (Although run out of memory after several seconds) I will try this on other PC. Btw, does it means that if I want to run on one PC, I should build it one that PC again? Thanks.
> 
> Update: I use the compiled program by PC with Nvidia graphics, on a AMD PC (ROG ally), it also works. But my ROG ally also run out of memory after few seconds...
> 
> Update2: I tried it on PC with GTX 2080, very smooth!!

You should be able to copy the build folder over

**Comment by xuyanging** [comment]
![image](https://github.com/user-attachments/assets/a59e594b-683d-42ce-8990-a08a9a9e05b0)
hi， I meet crash when runing, could any one help to solve it ?
